package ca.mcmaster.cas.se2aa4.a2.island.settlement.generator.settlement.settlementsGenerators;

import ca.mcmaster.cas.se2aa4.a2.island.geography.Land;
import ca.mcmaster.cas.se2aa4.a2.island.settlement.Settlement;
import ca.mcmaster.cas.se2aa4.a2.island.settlement.generator.settlement.AbstractSettlementsGenerator;
import ca.mcmaster.cas.se2aa4.a2.island.settlement.settlements.City;
import ca.mcmaster.cas.se2aa4.a2.island.settlement.settlements.Town;
import ca.mcmaster.cas.se2aa4.a2.island.settlement.settlements.Village;
import ca.mcmaster.cas.se2aa4.a2.island.tile.type.TileGroup;
import ca.mcmaster.cas.se2aa4.a2.mesh.adt.mesh.Mesh;
import ca.mcmaster.cas.se2aa4.a2.mesh.adt.vertex.Vertex;

import java.awt.*;
import java.util.*;
import java.util.List;

public class RandomSettlementsGenerator extends AbstractSettlementsGenerator {

    /**
     * Creates a generator that can generate a random set of settlements on the island.
     * @param mesh The {@link Mesh} to generate the {@link Settlement}'s on.
     * @param seed The seed that controls the {@link Random} locations of the {@link Settlement}s.
     * @param land The {@link Land} of the island.
     */
    public RandomSettlementsGenerator(Mesh mesh, long seed, Land land) {
        super(mesh, seed, land);
    }

    /**
     * Creates a random set of {@link Settlement}s.
     * @param numLocations The number of {@link Settlement}s to generate.
     */
    @Override
    public void createSettlements(int numLocations) {
        Set<Vertex> settlementLocations = getSettlementLocations(numLocations);

        settlementLocations.forEach(location -> {
            int chosenSettlementType = rand.nextInt(3);
            float settlementSize;

            if(chosenSettlementType == 0){
                settlementSize = rand.nextFloat(9,11);
                City city = new City(location, settlementSize);
                settlements.add(city);
            }
            else if (chosenSettlementType == 1) {
                settlementSize = rand.nextFloat(7,9);
                Town town = new Town(location, settlementSize);
                settlements.add(town);
            }
            else{
                settlementSize = rand.nextFloat(5,7);
                Village village = new Village(location, settlementSize);
                settlements.add(village);
            }
        });

        this.centralCity = settlements.stream().max(Comparator.comparing(Settlement::getSize)).get();
    }

    /**
     * Renders all the {@link Settlement}s generated by the createSettlements() function.
     */
    @Override
    public void renderSettlements() {
        this.settlements.forEach(settlement -> {
            if(settlement.equals(this.centralCity)){
                settlement.getLocation().setColor(new Color(255,0,0));
                settlement.getLocation().setThickness(settlement.getSize());
            }
            else if(settlement.getClass().equals(City.class)){
                settlement.getLocation().setColor(new Color(130, 130, 130));
                settlement.getLocation().setThickness(settlement.getSize());
            }
            else if (settlement.getClass().equals(Town.class)){
                settlement.getLocation().setColor(new Color(0,200,0));
                settlement.getLocation().setThickness(settlement.getSize());
            }
            else{
                settlement.getLocation().setColor(new Color(150,75,0));
                settlement.getLocation().setThickness(settlement.getSize());
            }
        });
    }

    /**
     * Generates random location for an amount of {@link Settlement}s as specified by the input parameter.
     * @param numLocations The number of locations to generate.
     * @return A {@link Set} of {@link Vertex}'s that describe the random locations of the {@link Settlement}s.
     */
    @Override
    public Set<Vertex> getSettlementLocations(int numLocations) {
        Set<Vertex> settlementLocations = new HashSet<>();

        List<Vertex> landVertices = new ArrayList<>();

        landTiles.forEach(tile -> {
            landVertices.add(tile.getPolygon().getCentroid());
        });

        for(int i = 0; i < numLocations; i++){

            Vertex nextLocation = landVertices.get(rand.nextInt(landVertices.size()));
            if(!settlementLocations.add(nextLocation)){
                i--;
            }
        }
        return settlementLocations;
    }


}
